apiVersion: apps/v1
kind: Deployment
metadata:
     name: dep
spec:
     replicas: 2
     selector:
          matchLabels:
               Key: q
       template:
              metadata:
                     name: ppname 
                     labels:  
                          Key: q                                 
                          Key: lab1                         
              spec:
                     containers:
                             - name: x1
                               image: deepakgonsalves63/imgjen
                              ports:
                                - containerPort: 8000
                     nodeSelector:
                              Key: n1
